### ISSUE TITLE
Improve Linux Compatibility, if it's not too much trouble (not urgent)

### ISSUE THREAD

**Issue by drPeidos** [DerekPascarella/Dreamcast-GDI-Quick-Patcher#1]
Hi!

Just reporting here my adventures with Linux.

So first I tried running the Perl script (I tried with Windows carriage returns and with Linux carriage returns), but I got this error:
`user@pc:/path/to/game$ perl gdi_quick_patcher.pl "Buzz Lightyear of Star Command v1.001 (2000)(Activision)(PAL)[!].gdi"

Dreamcast GDI Quick Patcher v1.1
A utility for easily applying region-free and VGA patches to a Dreamcast GDI.

Written by Derek Pascarella (ateam)

Apply region-free patch? (Y/N) y
Apply VGA patch? (Y/N) y

Processing "Buzz Lightyear of Star Command v1.001 (2000)(Activision)(PAL)[!].gdi"...

-> Found data track "track01.bin"...
Can't open file ".\track01.bin": No such file or directory at gdi_quick_patcher.pl line 297, <STDIN> line 2.

user@pc:/path/to/game$ perl gdi_quick_patcher.pl "Carrier v1.001 (2000)(XICAT Interactive)(PAL)(M4)[!].gdi"

Dreamcast GDI Quick Patcher v1.1
A utility for easily applying region-free and VGA patches to a Dreamcast GDI.

Written by Derek Pascarella (ateam)

Apply region-free patch? (Y/N) y
Apply VGA patch? (Y/N) y

Processing "Carrier v1.001 (2000)(XICAT Interactive)(PAL)(M4)[!].gdi"...

-> Found data track "track01.bin"...
Can't open file ".\track01.bin": No such file or directory at gdi_quick_patcher.pl line 297, <STDIN> line 2.`

If I run the EXE with Wine I get a different error:
`user@pc:/path/to/game$ wine gdi_quick_patcher.exe "Carrier v1.001 (2000)(XICAT Interactive)(PAL)(M4)[!].gdi"
Error writing "C:\users\user\Temp\par-76303065666d656d\cache-547d04937c728443cd32c4ed7
db94daddecd5736/0e796a00.dll.252": Permission denied at -e line 534.`
Inside the "~/.wine/drive_c/users/user/Temp/par-76303065666d656d/cache-547d04937c728443cd32c4ed7
db94daddecd5736" folder, everything has permissions to do whatever they want. Here's a pic showing the files inside that folder and it's permissions.
![imagem](https://github.com/user-attachments/assets/d5c00d61-7892-49c3-aa77-6f35897fd2b9)

Thanks.

**Comment by drPeidos** [comment]
Forgot to say, I have the following Perl version and I'm using the latest Linux Mint:
`perl -version

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 60 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall`

**Comment by DerekPascarella** [comment]
I never tested it on Linux. It's a path issue.

To fix, find all instances of `\\` in the script and replace with `/` so that Unix path format will be used.

**Comment by drPeidos** [comment]
It works :)
`perl gdi_quick_patcher.pl "Buzz Lightyear of Star Command v1.001 (2000)(Activision)(PAL)[!].gdi"

Dreamcast GDI Quick Patcher v1.1
A utility for easily applying region-free and VGA patches to a Dreamcast GDI.

Written by Derek Pascarella (ateam)

Apply region-free patch? (Y/N) y
Apply VGA patch? (Y/N) y

Processing "Buzz Lightyear of Star Command v1.001 (2000)(Activision)(PAL)[!].gdi"...

-> Found data track "track01.bin"...
    - No IP.BIN region strings found, skipping.
    - Patching IP.BIN headers for region flags...
       > Patched at decimal offset 64.
       > Patched at decimal offset 2416.
       > Patched at decimal offset 4768.
       > Patched at decimal offset 7120.
       > Patched at decimal offset 9472.
       > Patched at decimal offset 11824.
       > Patched at decimal offset 14176.
       > Patched at decimal offset 16528.
       > Patched at decimal offset 18880.
       > Patched at decimal offset 21232.
       > Patched at decimal offset 23584.
       > Patched at decimal offset 25936.
       > Patched at decimal offset 28288.
       > Patched at decimal offset 30640.
       > Patched at decimal offset 32992.
       > Patched at decimal offset 35344.
       > Patched at decimal offset 37704.
    - Patching IP.BIN headers for VGA flag...
       > Patched at decimal offset 77.
       > Patched at decimal offset 2429.
       > Patched at decimal offset 4781.
       > Patched at decimal offset 7133.
       > Patched at decimal offset 9485.
       > Patched at decimal offset 11837.
       > Patched at decimal offset 14189.
       > Patched at decimal offset 16541.
       > Patched at decimal offset 18893.
       > Patched at decimal offset 21245.
       > Patched at decimal offset 23597.
       > Patched at decimal offset 25949.
       > Patched at decimal offset 28301.
       > Patched at decimal offset 30653.
       > Patched at decimal offset 33005.
       > Patched at decimal offset 35357.
       > Patched at decimal offset 37717.
-> Found data track "track03.bin"...
    - Patching IP.BIN's region strings...
       > Patched at decimal offset 15924.
    - Patching IP.BIN headers for region flags...
       > Patched at decimal offset 64.
       > Patched at decimal offset 37704.
    - Patching IP.BIN headers for VGA flag...
       > Patched at decimal offset 77.
       > Patched at decimal offset 37717.
-> Found data track "track05.bin"...
    - No IP.BIN region strings found, skipping.
    - No IP.BIN header with region flags found, skipping.
    - No IP.BIN header with VGA flag found, skipping.

A total of 39 patches applied to GDI.

Press Enter to exit.`

I've attached the modified perl script, in case you want to make it available to more Linux users.
[gdi_quick_patcher_20241009linux.pl.zip](https://github.com/user-attachments/files/18150289/gdi_quick_patcher_20241009linux.pl.zip)
(2024-10-09 is the last commit date I found)

Thank you.

**Comment by DerekPascarella** [comment]
Happy to hear it! You're welcome.
